<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:Gestor" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:Gestor"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="urn:Gestor/types" elementFormDefault="qualified"/>
  </types>
  <message name="getEmployeeDetailsRequest">
    <part name="employeeId" type="xsd:string"/>
  </message>
  <message name="getEmployeeDetailsResponse">
    <part name="employeeDetails" type="xsd:string"/>
  </message>
  <portType name="GestorPortType">
    <operation name="getEmployeeDetails">
      <input message="tns:getEmployeeDetailsRequest"/>
      <output message="tns:getEmployeeDetailsResponse"/>
    </operation>
  </portType>
</definitions>