<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="urn:Vueling" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:Vueling"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <xsd:schema targetNamespace="urn:Vueling/types" elementFormDefault="qualified"/>
  </types>
  <message name="FlightRequestMessage">
    <part name="flightParameters" type="xsd:string"/>
  </message>
  <message name="PriceResponseMessage">
    <part name="price" type="xsd:string"/>
  </message>
  <portType name="VuelingPortType">
    <operation name="calcularPrecio">
      <input message="tns:FlightRequestMessage"/>
      <output message="tns:PriceResponseMessage"/>
    </operation>
  </portType>
</definitions>